// Generated from Spelling Bee word list.xlsx
// 原始單字庫 (順序不重要，程式會自動依照 A-Z 排序並重新編號)
const rawWordData = [
  { word: "a (an)", sentence: "I see a cat and an owl in the tree." },
  { word: "a few", sentence: "I have a few stickers left in my drawer." },
  { word: "a little", sentence: "I am a little bit hungry, so I will eat a cookie." },
  { word: "a lot", sentence: "There are a lot of stars in the sky tonight." },
  { word: "a.m.", sentence: "I wake up at seven a.m. to get ready for school." },
  { word: "able", sentence: "I am able to ride a bike now." },
  { word: "about", sentence: "This book is about a brave little elephant." },
  { word: "above", sentence: "The light is hanging above the dining table." },
  { word: "across", sentence: "Walk across the bridge to get to the park." },
  { word: "actor", sentence: "The actor is wearing a funny costume on stage." },
  { word: "actress", sentence: "My sister wants to be a famous actress one day." },
  { word: "adult", sentence: "You should always cross the street with an adult." },
  { word: "afraid", sentence: "The small mouse is afraid of the big cat." },
  { word: "after", sentence: "I usually brush my teeth after I eat dinner." },
  { word: "afternoon", sentence: "I do my homework in the afternoon." },
  { word: "again", sentence: "That was fun! Can we play the game again?" },
  { word: "age", sentence: "My brother is seven years of age." },
  { word: "ago", sentence: "We visited the zoo three weeks ago." },
  { word: "agree", sentence: "I agree with you; pizza is the best food!" },
  { word: "ahead", sentence: "Look ahead and watch where you are walking." },
  { word: "air", sentence: "We need fresh air to breathe and stay healthy." },
  { word: "airplane", sentence: "The airplane is flying high above the white clouds." },
  { word: "airport", sentence: "We went to the airport to catch our flight." },
  { word: "alive", sentence: "That plant is alive because I give it water." },
  { word: "all", sentence: "I finished all of my milk this morning." },
  { word: "along", sentence: "We walked along the river and saw many ducks." },
  { word: "also", sentence: "I like to draw, and I also like to sing." },
  { word: "although", sentence: "Although it was raining, we still had fun at the park." },
  { word: "am", sentence: "I am a happy student at this school." },
  { word: "an", sentence: "Please give me an apple for my snack." },
  { word: "angry", sentence: "Please don't be angry if I make a mistake." },
  { word: "animal", sentence: "Which animal is your favorite at the zoo?" },
  { word: "answer", sentence: "Please raise your hand if you know the answer." },
  { word: "ant", sentence: "Look at that tiny ant crawling on the leaf." },
  { word: "any", sentence: "Do you have any pencils I can borrow?" },
  { word: "apartment", sentence: "I live on the fifth floor of a tall apartment." },
  { word: "appear", sentence: "The sun will appear after the rain stops." },
  { word: "April", sentence: "The weather is usually very nice in April." },
  { word: "arm", sentence: "I hurt my arm while playing baseball." },
  { word: "around", sentence: "Let's run around the playground three times." },
  { word: "arrive", sentence: "What time did you arrive at school today?" },
  { word: "art", sentence: "I painted a colorful picture in art class." },
  { word: "as", sentence: "He is as tall as his older brother." },
  { word: "ask", sentence: "You can ask the teacher if you need help." },
  { word: "at", sentence: "We are staying at home today." },
  { word: "August", sentence: "I like to go to the beach in August." },
  { word: "aunt", sentence: "My aunt bought me a beautiful new dress." },
  { word: "away", sentence: "The bird flew away when it saw the cat." },
  { word: "baby", sentence: "The baby is sleeping in the crib." },
  { word: "back", sentence: "Please come back home before it gets dark." },
  { word: "bad", sentence: "It is a bad idea to run near the pool." },
  { word: "badminton", sentence: "I like to play badminton with my sister in the yard." },
  { word: "bag", sentence: "I put all my school books in my bag." },
  { word: "bake", sentence: "We are going to bake some chocolate cookies." },
  { word: "bakery", sentence: "The bread from the bakery smells very good." },
  { word: "balcony", sentence: "My mom grows colorful flowers on our balcony." },
  { word: "ball", sentence: "Let's play with the big blue ball." },
  { word: "balloon", sentence: "The clown gave me a big red balloon." },
  { word: "banana", sentence: "I like to eat a yellow banana for my snack." },
  { word: "band", sentence: "The school band plays music in the morning." },
  { word: "bank", sentence: "My dad puts his money in the bank." },
  { word: "barbecue", sentence: "We are having a barbecue in the garden tonight." },
  { word: "baseball", sentence: "He hit the baseball very far with his bat." },
  { word: "basket", sentence: "Please put the red apples into the basket." },
  { word: "basketball", sentence: "Can you throw the basketball into the net?" },
  { word: "bath", sentence: "I take a warm bath every night." },
  { word: "bathroom", sentence: "Please remember to wash your hands in the bathroom." },
  { word: "be", sentence: "Please be quiet while the teacher is speaking." },
  { word: "beach", sentence: "I like to play in the sand at the beach." },
  { word: "bean", sentence: "I like to eat green bean soup for lunch." },
  { word: "bear", sentence: "The brown bear is very big and fuzzy." },
  { word: "beautiful", sentence: "Look at that beautiful rainbow in the sky!" },
  { word: "become", sentence: "A caterpillar will become a beautiful butterfly." },
  { word: "bed", sentence: "I go to bed early every night." },
  { word: "bedroom", sentence: "I have a soft blue rug in my bedroom." },
  { word: "bee", sentence: "A bee is busy making honey." },
  { word: "beef", sentence: "We had beef and rice for dinner." },
  { word: "begin", sentence: "Let’s begin our English lesson now." },
  { word: "believe", sentence: "I believe that you can do a great job." },
  { word: "bell", sentence: "The school bell rings at eight o'clock." },
  { word: "belong", sentence: "These colorful pencils belong to me." },
  { word: "belt", sentence: "I wear a black belt with my pants." },
  { word: "bicycle", sentence: "I am learning how to ride my new bicycle." },
  { word: "big", sentence: "That is a very big elephant!" },
  { word: "bike", sentence: "I can ride my bike without any help." },
  { word: "bird", sentence: "A small bird is singing in the garden." },
  { word: "birthday", sentence: "I am having a party for my birthday today!" },
  { word: "bite", sentence: "Be careful not to bite your tongue." },
  { word: "black", sentence: "I have a pair of shiny black shoes." },
  { word: "blackboard", sentence: "The teacher writes the ABCs on the blackboard." },
  { word: "blanket", sentence: "I use a heavy blanket when it is cold at night." },
  { word: "blind", sentence: "A blind person uses a white cane to walk." },
  { word: "blow", sentence: "Blow the candles on your birthday cake!" },
  { word: "blue", sentence: "The sky is blue and the sun is bright." },
  { word: "boat", sentence: "We took a small boat across the lake." },
  { word: "body", sentence: "Exercise is very good for your body." },
  { word: "boil", sentence: "My mom will boil water to make noodles." },
  { word: "book", sentence: "I am reading a very funny book." },
  { word: "bookstore", sentence: "I want to buy a new storybook at the bookstore." },
  { word: "bored", sentence: "I feel bored when I have nothing to play with." },
  { word: "boring", sentence: "That movie was boring, so I fell asleep." },
  { word: "born", sentence: "I was born in the month of May." },
  { word: "borrow", sentence: "May I borrow your eraser for a minute?" },
  { word: "both", sentence: "I like both chocolate and vanilla." },
  { word: "bottle", sentence: "Please drink some water from your bottle." },
  { word: "bowl", sentence: "I ate a big bowl of cereal." },
  { word: "box", sentence: "There is a toy inside the heavy box." },
  { word: "boy", sentence: "The boy is playing soccer with his friends." },
  { word: "brave", sentence: "The brave firefighter saved the little cat." },
  { word: "bread", sentence: "I like to eat bread with butter for breakfast." },
  { word: "break", sentence: "Be careful not to break the glass bowl." },
  { word: "bridge", sentence: "We walked across the long bridge over the river." },
  { word: "bright", sentence: "The sun is very bright today; wear your hat." },
  { word: "bring", sentence: "Please bring your notebook to class tomorrow." },
  { word: "brother", sentence: "I have one older brother and one younger sister." },
  { word: "brown", sentence: "The big dog has soft brown fur." },
  { word: "brush", sentence: "You should brush your teeth every morning and night." },
  { word: "bug", sentence: "I saw a little green bug on the leaf." },
  { word: "build", sentence: "I want to build a tall tower with these blocks." },
  { word: "building", sentence: "That school is a very large and tall building." },
  { word: "bun", sentence: "I ate a sweet bun for my afternoon snack." },
  { word: "burn", sentence: "Don't touch the stove, or you might burn your hand." },
  { word: "bus", sentence: "I wait for the school bus every morning." },
  { word: "businessman", sentence: "The businessman carries a black bag to his office." },
  { word: "busy", sentence: "The bees are very busy making honey." },
  { word: "but", sentence: "I like apples, but I do not like grapes." },
  { word: "butterfly", sentence: "A beautiful butterfly landed on my hand." },
  { word: "buy", sentence: "I want to buy a new book today." },
  { word: "by", sentence: "The cat is sitting by the window." },
  { word: "cage", sentence: "The pet bird lives in a big, clean cage." },
  { word: "cake", sentence: "I had a big cake for my birthday." },
  { word: "call", sentence: "Please call me when you get home." },
  { word: "camp", sentence: "We go to summer camp every year." },
  { word: "can", sentence: "I can ride a bicycle without help." },
  { word: "candy", sentence: "I ate a piece of sweet candy after lunch." },
  { word: "cap", sentence: "He wears a blue cap to protect his head." },
  { word: "car", sentence: "My dad drives a red car to work." },
  { word: "card", sentence: "I wrote a thank-you card for my teacher." },
  { word: "care", sentence: "We must take care of our pets." },
  { word: "careful", sentence: "Be careful when you cross the busy street." },
  { word: "carry", sentence: "Can you help me carry these heavy books?" },
  { word: "case", sentence: "I keep my pencils in a plastic case." },
  { word: "castle", sentence: "The king and queen live in a beautiful castle." },
  { word: "cat", sentence: "My cat likes to sleep on the sofa." },
  { word: "catch", sentence: "Try to catch the ball with both hands." },
  { word: "celebrate", sentence: "We will celebrate your birthday with a party." },
  { word: "cell phone", sentence: "My mom is talking on her cell phone right now." },
  { word: "cent", sentence: "One dollar is the same as one hundred cents." },
  { word: "centimeter", sentence: "My pencil is about fifteen centimeters long." },
  { word: "chair", sentence: "Please sit on the chair and listen to the story." },
  { word: "chalk", sentence: "The teacher uses white chalk to write on the board." },
  { word: "change", sentence: "We need to change our clothes after gym class." },
  { word: "cheap", sentence: "This notebook is very cheap; it only costs ten dollars." },
  { word: "check", sentence: "Please check your homework for any mistakes." },
  { word: "cheer", sentence: "Let's cheer for our team during the game." },
  { word: "cheese", sentence: "I want a ham and cheese sandwich." },
  { word: "cherry", sentence: "There is a red cherry on top of my ice cream." },
  { word: "chess", sentence: "My grandpa is teaching me how to play chess." },
  { word: "chew", sentence: "You should chew your food well." },
  { word: "chicken", sentence: "The chicken on the farm laid an egg." },
  { word: "child", sentence: "Every child in the class got a free sticker." },
  { word: "China", sentence: "My uncle lives in a big city in China." },
  { word: "Chinese", sentence: "I am learning how to speak Chinese at school." },
  { word: "chocolate", sentence: "I love to eat chocolate cookies with milk." },
  { word: "choose", sentence: "You can choose one toy from the toy box." },
  { word: "chop", sentence: "My dad will chop the wood for the fire." },
  { word: "chopsticks", sentence: "I use chopsticks to eat my noodles and rice." },
  { word: "Christmas", sentence: "We put up a tall tree for Christmas in December." },
  { word: "church", sentence: "We can see the tall tower of the church." },
  { word: "circle", sentence: "Draw a red dot in the middle of the circle." },
  { word: "city", sentence: "We live in a very big and noisy city." },
  { word: "clap", sentence: "Let's clap our hands to the music." },
  { word: "class", sentence: "I have many good friends in my English class." },
  { word: "classroom", sentence: "Our classroom has many colorful posters on the wall." },
  { word: "clean", sentence: "Please clean your room before you go out to play." },
  { word: "clear", sentence: "The water in the mountain stream is very clear." },
  { word: "clerk", sentence: "The clerk at the store helped us find the milk." },
  { word: "climb", sentence: "Be careful when you climb the tall tree." },
  { word: "clock", sentence: "Look at the clock; it is time for lunch!" },
  { word: "close", sentence: "Please close the door quietly when you leave." },
  { word: "closet", sentence: "I hang my school clothes inside the closet." },
  { word: "cloudy", sentence: "It is cloudy today, so we cannot see the sun." },
  { word: "club", sentence: "I joined the art club to learn how to paint." },
  { word: "coat", sentence: "Wear a warm coat because it is cold outside." },
  { word: "cold", sentence: "It is very cold in the winter." },
  { word: "collect", sentence: "I like to collect beautiful shells at the beach." },
  { word: "color", sentence: "What is your favorite color, red or blue?" },
  { word: "comb", sentence: "I use a comb to make my hair look neat." },
  { word: "come", sentence: "Please come here and sit down." },
  { word: "comfortable", sentence: "My new bed is very soft and comfortable." },
  { word: "comic", sentence: "This comic book has many funny pictures." },
  { word: "common", sentence: "Dogs are common pets for many families." },
  { word: "computer", sentence: "We use a computer to learn English in class." },
  { word: "convenient", sentence: "The shop is near my house, so it is convenient." },
  { word: "cook", sentence: "My dad is a very good cook." },
  { word: "cool", sentence: "The fan makes the room feel cool." },
  { word: "copy", sentence: "Please copy the words from the board." },
  { word: "corner", sentence: "Please put the trash can in the corner of the room." },
  { word: "correct", sentence: "Please correct the mistakes in your sentence." },
  { word: "cost", sentence: "How much does this new toy cost?" },
  { word: "couch", sentence: "My cat likes to sleep on the soft couch." },
  { word: "count", sentence: "Can you count from one to twenty in English?" },
  { word: "country", sentence: "I live in a beautiful country with many mountains." },
  { word: "cousin", sentence: "I like to play games with my cousin on Sundays." },
  { word: "cover", sentence: "Use a cover to keep the food warm." },
  { word: "cow", sentence: "The cow on the farm gives us fresh milk." },
  { word: "cowboy", sentence: "The cowboy is riding a big brown horse." },
  { word: "crazy", sentence: "The monkeys in the zoo are acting very crazy." },
  { word: "cross", sentence: "Always look both ways before you cross the street." },
  { word: "cry", sentence: "The little baby started to cry because he was hungry." },
  { word: "cup", sentence: "I drink a cup of milk every morning." },
  { word: "cupboard", sentence: "The cups and plates are inside the kitchen cupboard." },
  { word: "cut", sentence: "Be careful when you cut the paper." },
  { word: "cute", sentence: "That small puppy is so cute and fluffy." },
  { word: "dance", sentence: "Let's dance to the happy music!" },
  { word: "dangerous", sentence: "It is dangerous to play with fire." },
  { word: "dark", sentence: "I use a small lamp because I am afraid of the dark." },
  { word: "date", sentence: "Do you know the date of your birthday?" },
  { word: "daughter", sentence: "She is the only daughter in her family." },
  { word: "day", sentence: "Today is a beautiful and sunny day." },
  { word: "dead", sentence: "We found some dead leaves on the ground." },
  { word: "dear", sentence: "My mother is a very dear person to me." },
  { word: "December", sentence: "We have a big party in December." },
  { word: "decide", sentence: "I cannot decide between the red or blue pen." },
  { word: "deer", sentence: "We saw a brown deer running in the forest." },
  { word: "delicious", sentence: "My mom made a delicious chocolate cake." },
  { word: "dentist", sentence: "The dentist told me to brush my teeth every day." },
  { word: "desk", sentence: "I sit at my desk to do my homework every day." },
  { word: "dictionary", sentence: "Use a dictionary to find the meaning of new words." },
  { word: "die", sentence: "Plants will die if they do not get enough water." },
  { word: "different", sentence: "Every snowflake has a different shape." },
  { word: "difficult", sentence: "This math problem is a bit difficult to solve." },
  { word: "dig", sentence: "My dog likes to dig holes in the garden." },
  { word: "dining room", sentence: "We eat dinner together in the dining room." },
  { word: "dinosaur", sentence: "I have a toy dinosaur with big teeth." },
  { word: "dirty", sentence: "Your shoes are dirty from playing in the mud." },
  { word: "dish", sentence: "Please put your dirty dish in the kitchen sink." },
  { word: "do", sentence: "What do you want to do after school?" },
  { word: "doctor", sentence: "I go to see the doctor when I feel sick." },
  { word: "dodge ball", sentence: "We like to play dodge ball during gym class." },
  { word: "dog", sentence: "My dog likes to bark at the mailman." },
  { word: "doll", sentence: "My sister likes to play with her favorite doll." },
  { word: "dollar", sentence: "This pencil costs only one dollar." },
  { word: "dolphin", sentence: "A dolphin is a very smart animal that lives in the sea." },
  { word: "door", sentence: "Please close the door quietly when you leave." },
  { word: "dot", sentence: "Draw a red dot in the middle of the circle." },
  { word: "down", sentence: "Walk down the stairs carefully, please." },
  { word: "dragonfly", sentence: "A dragonfly has four wings and flies fast." },
  { word: "draw", sentence: "I like to draw pictures of cats and dogs." },
  { word: "drawer", sentence: "My socks are in the top drawer of the desk." },
  { word: "dream", sentence: "I had a funny dream about a flying cat last night." },
  { word: "dress", sentence: "The girl is wearing a beautiful pink dress." },
  { word: "drink", sentence: "I drink a cup of milk every morning." },
  { word: "drive", sentence: "My dad drives a red car to work." },
  { word: "driver", sentence: "The bus driver is very kind to all the students." },
  { word: "drop", sentence: "Be careful not to drop the glass of milk." },
  { word: "drum", sentence: "My brother likes to play the drum very loudly." },
  { word: "dry", sentence: "Use a towel to make your hands dry." },
  { word: "duck", sentence: "The yellow duck is swimming in the pond." },
  { word: "each", sentence: "Each student in the class has a red pencil." },
  { word: "eagle", sentence: "The eagle flies very high in the blue sky." },
  { word: "ear", sentence: "I can hear the music with my ear." },
  { word: "early", sentence: "I wake up early to get ready for school." },
  { word: "earth", sentence: "The earth is the planet where we all live." },
  { word: "east", sentence: "The sun rises in the east every morning." },
  { word: "easy", sentence: "This math problem is very easy to solve." },
  { word: "eat", sentence: "I like to eat pizza for dinner." },
  { word: "egg", sentence: "We had a boiled egg for breakfast." },
  { word: "eight", sentence: "An octopus has eight long arms to swim with." },
  { word: "eighty", sentence: "There are eighty trees in the big park." },
  { word: "elementary school", sentence: "I am a student in the second grade of elementary school." },
  { word: "elephant", sentence: "An elephant has a very long nose called a trunk." },
  { word: "eleven", sentence: "There are eleven players on a soccer team." },
  { word: "else", sentence: "Is there anything else you want to eat?" },
  { word: "e-mail", sentence: "My teacher sent an e-mail to my parents today." },
  { word: "end", sentence: "This is the end of the long movie." },
  { word: "engineer", sentence: "An engineer knows how to build strong bridges." },
  { word: "English", sentence: "We are learning many new English words today." },
  { word: "enjoy", sentence: "I really enjoy playing soccer with my friends." },
  { word: "enough", sentence: "I have enough stickers for everyone to have one." },
  { word: "enter", sentence: "Please knock on the door before you enter." },
  { word: "envelope", sentence: "I put the letter inside a white envelope." },
  { word: "even", sentence: "My sister is tall, and she is even taller than me." },
  { word: "evening", sentence: "We eat dinner together in the evening." },
  { word: "ever", sentence: "Have you ever seen a real elephant?" },
  { word: "every", sentence: "I brush my teeth every morning and night." },
  { word: "excellent", sentence: "You did an excellent job on your drawing!" },
  { word: "excited", sentence: "I am so excited about my birthday party!" },
  { word: "exciting", sentence: "Roller coasters are very exciting to ride." },
  { word: "exercise", sentence: "It is good to exercise and move your body." },
  { word: "expensive", sentence: "That big toy robot is too expensive to buy." },
  { word: "experience", sentence: "Seeing a real whale was a wonderful experience." },
  { word: "eye", sentence: "I have dust in my left eye." },
  { word: "face", sentence: "Please wash your face before you go to bed." },
  { word: "fact", sentence: "It is a fact that the earth goes around the sun." },
  { word: "factory", sentence: "My uncle works in a big factory that makes toys." },
  { word: "fail", sentence: "If you do not study, you might fail the test." },
  { word: "fall", sentence: "Watch out! Do not fall off the chair." },
  { word: "family", sentence: "I love to eat dinner with my family every night." },
  { word: "famous", sentence: "He is a famous singer that everyone knows." },
  { word: "fan", sentence: "Please turn on the fan; it is very hot." },
  { word: "far", sentence: "The park is very far from my house." },
  { word: "farm", sentence: "We saw many cows and pigs on the farm." },
  { word: "farmer", sentence: "The farmer grows corn and rice on his land." },
  { word: "fast", sentence: "A rabbit can run very fast across the grass." },
  { word: "fat", sentence: "The neighbor has a very fat cat." },
  { word: "father", sentence: "My father helps me with my math homework." },
  { word: "favorite", sentence: "Blue is my favorite color in the whole world." },
  { word: "February", sentence: "February is the shortest month of the year." },
  { word: "feed", sentence: "I help my mom feed our pet fish every day." },
  { word: "feel", sentence: "I feel very happy when I play with my friends." },
  { word: "fever", sentence: "I stayed home because I had a high fever." },
  { word: "few", sentence: "I have a few friends coming over to play." },
  { word: "fifty", sentence: "This storybook has fifty beautiful pages." },
  { word: "fight", sentence: "Friends should not fight over their toys." },
  { word: "fill", sentence: "Please fill the glass with some cold water." },
  { word: "find", sentence: "Can you help me find my lost toy car?" },
  { word: "fine", sentence: "I am feeling fine today, thank you for asking." },
  { word: "finger", sentence: "I have five fingers on my right hand." },
  { word: "finish", sentence: "I want to finish my drawing before dinner." },
  { word: "fire", sentence: "The campfire is a bright and hot fire." },
  { word: "fish", sentence: "My little gold fish swims in a small bowl." },
  { word: "fisherman", sentence: "The fisherman caught many fish in the big net." },
  { word: "five", sentence: "I have five fingers on my right hand." },
  { word: "fix", sentence: "My dad can fix my broken toy car." },
  { word: "flamingo", sentence: "A flamingo is a tall bird with pink feathers." },
  { word: "floor", sentence: "Please pick up your toys from the floor." },
  { word: "flute", sentence: "She plays a beautiful song on her silver flute." },
  { word: "fly", sentence: "A bird can fly high in the sky." },
  { word: "follow", sentence: "Please follow the teacher to the library." },
  { word: "food", sentence: "We must eat healthy food to grow strong." },
  { word: "foot", sentence: "I put a sock on my left foot." },
  { word: "for", sentence: "This birthday gift is for you." },
  { word: "foreign", sentence: "We are learning a foreign language at school." },
  { word: "foreigner", sentence: "The foreigner is visiting our city for the first time." },
  { word: "forget", sentence: "Please don't forget to bring your homework." },
  { word: "fork", sentence: "I use a fork and a spoon to eat my dinner." },
  { word: "forty", sentence: "My father is forty years old this year." },
  { word: "four", sentence: "A dog has four legs to help it run very fast." },
  { word: "fox", sentence: "The orange fox hid behind the bushes." },
  { word: "free", sentence: "You can have this sticker; it is free." },
  { word: "fresh", sentence: "These apples are very sweet and fresh." },
  { word: "Friday", sentence: "We are happy because Friday is almost the weekend." },
  { word: "friend", sentence: "You are my best friend in the whole school." },
  { word: "friendly", sentence: "Our neighbor has a very friendly dog." },
  { word: "frisbee", sentence: "Throw the frisbee to me and I will catch it!" },
  { word: "frog", sentence: "A green frog jumped into the deep water." },
  { word: "from", sentence: "I got a beautiful card from my best friend." },
  { word: "front", sentence: "My dog likes to sit in front of the house." },
  { word: "fruit", sentence: "Apples and grapes are my favorite kinds of fruit." },
  { word: "fry", sentence: "We can fry some eggs in the pan." },
  { word: "full", sentence: "My stomach is full after eating dinner." },
  { word: "fun", sentence: "Playing games with you is always fun." },
  { word: "funny", sentence: "That clown told a very funny joke." },
  { word: "game", sentence: "Let's play a fun game during our break time." },
  { word: "garbage", sentence: "Please put your garbage in the trash can." },
  { word: "garden", sentence: "There are many red roses in our garden." },
  { word: "gas", sentence: "The car needs gas to move." },
  { word: "gate", sentence: "Please close the gate so the dog stays inside." },
  { word: "gentleman", sentence: "That gentleman opened the door for my mother." },
  { word: "get", sentence: "I need to get my jacket from the room." },
  { word: "ghost", sentence: "He wore a white sheet to look like a ghost." },
  { word: "giant", sentence: "The giant in the story was as tall as a house." },
  { word: "gift", sentence: "I bought a nice gift for my mother's birthday." },
  { word: "girl", sentence: "The girl is wearing a pretty pink dress." },
  { word: "give", sentence: "Please give me a piece of paper." },
  { word: "glad", sentence: "I am very glad to see you today." },
  { word: "glass", sentence: "I drink a glass of cold milk every morning." },
  { word: "glue", sentence: "Use the glue to stick the picture on the paper." },
  { word: "go", sentence: "Let's go to the zoo this weekend." },
  { word: "goat", sentence: "The goat is eating grass on the hill." },
  { word: "good", sentence: "You did a very good job on your drawing." },
  { word: "goose", sentence: "A white goose is walking near the river." },
  { word: "grandfather", sentence: "My grandfather tells me many old stories." },
  { word: "grandmother", sentence: "My grandmother gives me the best hugs." },
  { word: "grape", sentence: "I like to eat a sweet purple grape." },
  { word: "grass", sentence: "The grass in the park is very soft and green." },
  { word: "gray", sentence: "The sky is gray because it is going to rain." },
  { word: "great", sentence: "We had a great time at the zoo yesterday." },
  { word: "green", sentence: "The grass in the park is very green and fresh." },
  { word: "grow", sentence: "Plants need water and sun to grow big." },
  { word: "guava", sentence: "A guava is a fruit that is pink inside." },
  { word: "guess", sentence: "Can you guess what is inside this box?" },
  { word: "guitar", sentence: "My brother is learning how to play the guitar." },
  { word: "gym", sentence: "We play basketball in the school gym." },
  { word: "hair", sentence: "My sister has very long and black hair." },
  { word: "half", sentence: "I will share my apple and give you half." },
  { word: "ham", sentence: "I want a ham and cheese sandwich." },
  { word: "hand", sentence: "Please raise your hand if you have a question." },
  { word: "hang", sentence: "I hang my jacket on the hook behind the door." },
  { word: "happen", sentence: "Strange things always happen in fairy tales." },
  { word: "happy", sentence: "I am a happy student at this school." },
  { word: "hard", sentence: "The rock is very hard and heavy." },
  { word: "hat", sentence: "Take off your hat when you are inside." },
  { word: "hate", sentence: "I hate it when it is too hot to play outside." },
  { word: "have", sentence: "I have two older brothers and one sister." },
  { word: "he", sentence: "He is the tallest student in our class." },
  { word: "head", sentence: "I wear a blue hat on my head." },
  { word: "headache", sentence: "I have a headache, so I need to rest quietly." },
  { word: "health", sentence: "Eating vegetables is very important for your health." },
  { word: "healthy", sentence: "Eating fruit is a healthy habit for kids." },
  { word: "hear", sentence: "I can hear the music with my ear." },
  { word: "heat", sentence: "I can feel the heat from the hot oven." },
  { word: "heavy", sentence: "This bag of books is too heavy for me to lift." },
  { word: "help", sentence: "Can you help me tie my shoes, please?" },
  { word: "here", sentence: "Please come here and look at this bug." },
  { word: "hi", sentence: "Please say hi to your mother for me." },
  { word: "hide", sentence: "Let's play hide and seek in the garden." },
  { word: "high", sentence: "The bird is flying very high in the sky." },
  { word: "hill", sentence: "We ran down the green hill together." },
  { word: "hippo", sentence: "A hippo likes to stay in the water to keep cool." },
  { word: "hit", sentence: "Do not hit the ball toward the window." },
  { word: "hobby", sentence: "My favorite hobby is drawing pictures of animals." },
  { word: "hold", sentence: "Please hold my hand when we cross the street." },
  { word: "holiday", sentence: "We are going to the beach for our summer holiday." },
  { word: "home", sentence: "We are staying at home today." },
  { word: "homework", sentence: "I always finish my homework before I watch TV." },
  { word: "honest", sentence: "It is always better to be honest and tell the truth." },
  { word: "hop", sentence: "Watch the rabbit hop across the grass." },
  { word: "hope", sentence: "I hope you have a wonderful birthday today." },
  { word: "horse", sentence: "I want to ride a big brown horse one day." },
  { word: "hospital", sentence: "The doctor works in a very large hospital." },
  { word: "hot", sentence: "Be careful; the soup is very hot." },
  { word: "hotel", sentence: "We stayed in a nice hotel during our vacation." },
  { word: "hour", sentence: "We will go to the park in one hour." },
  { word: "house", sentence: "My house has a red roof and a white door." },
  { word: "housewife", sentence: "My mom is a housewife who takes care of our home." },
  { word: "how", sentence: "How do you spell your name?" },
  { word: "hundred", sentence: "I want to live for a hundred years!" },
  { word: "hungry", sentence: "I am hungry, so I want to eat a sandwich." },
  { word: "hurry", sentence: "We must hurry so we are not late for school." },
  { word: "hurt", sentence: "I hurt my arm while playing baseball." },
  { word: "husband", sentence: "My father is my mother's husband." },
  { word: "I", sentence: "I love to draw pictures of animals." },
  { word: "ice", sentence: "I like to have ice in my water." },
  { word: "ice cream", sentence: "Vanilla is my favorite flavor of ice cream." },
  { word: "idea", sentence: "I have a great idea for our new art project!" },
  { word: "if", sentence: "We can go out if it stops raining." },
  { word: "important", sentence: "It is important to listen to the teacher." },
  { word: "in", sentence: "The key is in the kitchen drawer." },
  { word: "insect", sentence: "An ant is a small insect with six legs." },
  { word: "interested", sentence: "I am interested in learning about space." },
  { word: "interesting", sentence: "This book about dinosaurs is very interesting." },
  { word: "internet", sentence: "We can find many cool videos on the internet." },
  { word: "interview", sentence: "The reporter had an interview with the famous singer." },
  { word: "invite", sentence: "I will invite all my friends to my party." },
  { word: "is", sentence: "The sky is very blue today." },
  { word: "island", sentence: "An island is a piece of land with water all around it." },
  { word: "it", sentence: "Pick up the toy and put it away." },
  { word: "jacket", sentence: "Please wear your jacket because it is cold outside." },
  { word: "January", sentence: "January is the very first month of the year." },
  { word: "jeans", sentence: "I am wearing my favorite blue jeans today." },
  { word: "job", sentence: "My father has a very interesting job." },
  { word: "jog", sentence: "My mother likes to jog in the park every morning." },
  { word: "join", sentence: "Would you like to join us for lunch?" },
  { word: "joy", sentence: "The children jumped for joy when they saw the cake." },
  { word: "juice", sentence: "I like to drink cold orange juice in the morning." },
  { word: "July", sentence: "It is very hot and sunny in July." },
  { word: "jump", sentence: "Can you jump as high as a kangaroo?" },
  { word: "June", sentence: "Summer usually starts in the month of June." },
  { word: "junior high school", sentence: "My older brother goes to junior high school now." },
  { word: "just", sentence: "I just finished my breakfast a minute ago." },
  { word: "kangaroo", sentence: "A kangaroo can hop very far with its strong legs." },
  { word: "keep", sentence: "Please keep your desk clean and tidy." },
  { word: "key", sentence: "I used a key to open the front door." },
  { word: "kick", sentence: "I like to kick the ball into the soccer net." },
  { word: "kid", sentence: "The kid is wearing a bright yellow shirt." },
  { word: "kill", sentence: "We should not kill the spiders in the garden." },
  { word: "kilo", sentence: "I bought one kilo of sweet red apples." },
  { word: "kilogram", sentence: "This heavy bag of rice weighs five kilograms." },
  { word: "kind", sentence: "My teacher is very kind and helpful." },
  { word: "king", sentence: "The king lives in a very large and beautiful palace." },
  { word: "kiss", sentence: "My mother gives me a kiss before I go to sleep." },
  { word: "kitchen", sentence: "My grandmother is cooking dinner in the kitchen." },
  { word: "kite", sentence: "I love to fly my red kite on a windy day." },
  { word: "kitten", sentence: "The small kitten likes to play with string." },
  { word: "knee", sentence: "I hurt my knee when I fell down." },
  { word: "knife", sentence: "Use a knife to cut the bread into small pieces." },
  { word: "knock", sentence: "Please knock on the door before you enter." },
  { word: "know", sentence: "Do you know how to spell your name?" },
  { word: "knowledge", sentence: "Reading books helps you get more knowledge." },
  { word: "koala", sentence: "A koala likes to sleep in the trees in Australia." },
  { word: "lake", sentence: "We went to the lake to see the ducks swimming." },
  { word: "lamb", sentence: "A lamb is a baby sheep with soft white wool." },
  { word: "lamp", sentence: "I turn on my lamp to read books at night." },
  { word: "language", sentence: "We are learning how to speak the English language." },
  { word: "large", sentence: "An elephant is a very large animal." },
  { word: "laugh", sentence: "That funny clown made all the children laugh." },
  { word: "lawyer", sentence: "A lawyer helps people understand the rules." },
  { word: "lazy", sentence: "My cat is lazy and sleeps all day long." },
  { word: "leader", sentence: "He is the leader of our school soccer team." },
  { word: "learn", sentence: "We go to school to learn many new things." },
  { word: "leave", sentence: "It is time to leave and go home now." },
  { word: "leg", sentence: "The table has one broken leg." },
  { word: "lemon", sentence: "A lemon is yellow and tastes very sour." },
  { word: "lend", sentence: "Can you lend me a pencil for a moment?" },
  { word: "let", sentence: "Please let me help you carry those bags." },
  { word: "lettuce", sentence: "I like to have fresh lettuce in my sandwich." },
  { word: "library", sentence: "We must be very quiet when we are in the library." },
  { word: "lid", sentence: "Put the lid back on the jar of jam." },
  { word: "lie", sentence: "It is not good to tell a lie to your parents." },
  { word: "light", sentence: "The light is hanging above the dining table." },
  { word: "lion", sentence: "The lion is the king of the animals." },
  { word: "lip", sentence: "Be careful not to bite your lip while eating." },
  { word: "listen", sentence: "Please listen carefully to what the teacher says." },
  { word: "little", sentence: "The little boy is playing with his toy car." },
  { word: "live", sentence: "I want to live for a hundred years!" },
  { word: "living room", sentence: "We watch television together in the living room." },
  { word: "lizard", sentence: "I saw a small lizard climbing on the wall." },
  { word: "lonely", sentence: "I feel lonely when I have no one to play with." },
  { word: "long", sentence: "A snake has a very long body." },
  { word: "look", sentence: "Look at the clock; it is time for lunch!" },
  { word: "lose", sentence: "Be careful not to lose your lunch money." },
  { word: "loud", sentence: "The drum is very loud." },
  { word: "love", sentence: "I love to draw pictures of animals." },
  { word: "lovely", sentence: "You have a lovely smile on your face." },
  { word: "low", sentence: "The sun is low in the sky during the evening." },
  { word: "lucky", sentence: "I am lucky because I found a four-leaf clover." },
  { word: "lunch", sentence: "We eat our lunch at noon every day." },
  { word: "machine", sentence: "A washing machine helps us clean our clothes." },
  { word: "mad", sentence: "Please don't be mad at me for breaking the toy." },
  { word: "magazine", sentence: "My mother is reading a magazine about cooking." },
  { word: "magic", sentence: "The magician showed us a very cool magic trick." },
  { word: "mail", sentence: "The mailman brought some mail to our house." },
  { word: "mailman", sentence: "My dog likes to bark at the mailman." },
  { word: "make", sentence: "I can make a paper airplane." },
  { word: "man", sentence: "That man is my favorite English teacher." },
  { word: "many", sentence: "There are many red roses in our garden." },
  { word: "map", sentence: "We used a map to find the way to the zoo." },
  { word: "March", sentence: "Flowers start to grow in the month of March." },
  { word: "market", sentence: "My mom buys fresh fruit at the market." },
  { word: "marker", sentence: "Use a red marker to draw a big circle." },
  { word: "marry", sentence: "The prince and princess will marry today." },
  { word: "mat", sentence: "Please wipe your shoes on the mat." },
  { word: "math", sentence: "This math problem is very easy to solve." },
  { word: "matter", sentence: "It does not matter if you make a mistake." },
  { word: "May", sentence: "May I go to the restroom, please?" },
  { word: "maybe", sentence: "Maybe we can go to the park later." },
  { word: "me", sentence: "My grandmother gave me a beautiful gift." },
  { word: "meal", sentence: "Dinner is the most important meal for my family." },
  { word: "mean", sentence: "What does this new English word mean?" },
  { word: "meat", sentence: "The meat was very tough and hard to chew." },
  { word: "medicine", sentence: "The doctor gave me medicine to help me get well." },
  { word: "meet", sentence: "I will meet you at the park after school." },
  { word: "menu", sentence: "Let's look at the menu to choose our food." },
  { word: "message", sentence: "I left a message for my friend on the phone." },
  { word: "milk", sentence: "I drink a cup of milk every morning." },
  { word: "million", sentence: "There are a million stars in the night sky." },
  { word: "minute", sentence: "Please wait for one minute; I am almost ready." },
  { word: "miss", sentence: "I will miss you when you go on vacation." },
  { word: "mistake", sentence: "It is OK to make mistakes when you learn." },
  { word: "modern", sentence: "This big city has many modern buildings." },
  { word: "mom", sentence: "My mom likes to drink hot tea in the morning." },
  { word: "Monday", sentence: "We go back to school every Monday morning." },
  { word: "money", sentence: "My dad puts his money in the bank." },
  { word: "monkey", sentence: "The monkeys in the zoo are acting very crazy." },
  { word: "month", sentence: "My favorite month is December because of Christmas." },
  { word: "moon", sentence: "I can see the moon and stars at night." },
  { word: "mop", sentence: "I need a mop to clean the water on the floor." },
  { word: "more", sentence: "Do you want some more cake?" },
  { word: "morning", sentence: "I wait for the school bus every morning." },
  { word: "mosquito", sentence: "A mosquito bit my arm and now it is itchy." },
  { word: "mother", sentence: "Please say hi to your mother for me." },
  { word: "motorcycle", sentence: "My dad rides a motorcycle to go to work." },
  { word: "mountain", sentence: "We saw white snow on top of the tall mountain." },
  { word: "mouse", sentence: "The small mouse is afraid of the big cat." },
  { word: "mouth", sentence: "Use your mouth to speak clearly and smile." },
  { word: "move", sentence: "The car needs gas to move." },
  { word: "movie", sentence: "This is the end of the long movie." },
  { word: "Mr.", sentence: "Mr. Wang is our school principal." },
  { word: "Mrs.", sentence: "Mrs. Lee teaches us how to sing." },
  { word: "MRT", sentence: "We take the MRT to go to the big city." },
  { word: "Ms.", sentence: "Ms. White is very kind to all the students." },
  { word: "much", sentence: "How much does this new toy cost?" },
  { word: "mud", sentence: "Don't walk in the mud with your new shoes!" },
  { word: "museum", sentence: "We saw old dinosaurs at the big museum." },
  { word: "music", sentence: "I can hear the music with my ear." },
  { word: "my", sentence: "My cat likes to sleep on the sofa." },
  { word: "name", sentence: "How do you spell your name?" },
  { word: "narrow", sentence: "The path is very narrow, so walk carefully." },
  { word: "near", sentence: "It is a bad idea to run near the pool." },
  { word: "neck", sentence: "I wear a warm scarf around my neck." },
  { word: "need", sentence: "I need to get my jacket from the room." },
  { word: "neighbor", sentence: "The neighbor has a very fat cat." },
  { word: "nephew", sentence: "My father's nephew is my cousin." },
  { word: "never", sentence: "I have never seen a ghost." },
  { word: "new", sentence: "I want to buy a new book today." },
  { word: "news", sentence: "The reporter is telling the news on television." },
  { word: "newspaper", sentence: "My grandfather reads the newspaper every morning." },
  { word: "next", sentence: "Who is the next person in line?" },
  { word: "nice", sentence: "It was a nice and sunny day for a picnic." },
  { word: "night", sentence: "I go to bed early every night." },
  { word: "nine", sentence: "There are nine colorful pencils in my box." },
  { word: "ninety", sentence: "This new toy costs ninety dollars." },
  { word: "no", sentence: "There is no milk left in the fridge." },
  { word: "nod", sentence: "Please nod your head if you understand the rules." },
  { word: "noise", sentence: "The drum makes a loud noise." },
  { word: "noisy", sentence: "We live in a very big and noisy city." },
  { word: "noodles", sentence: "My mom will boil water to make noodles." },
  { word: "noon", sentence: "We eat our lunch at noon every day." },
  { word: "north", sentence: "The birds are flying north for the summer." },
  { word: "nose", sentence: "An elephant has a very long nose called a trunk." },
  { word: "not", sentence: "I like apples, but I do not like grapes." },
  { word: "notebook", sentence: "Please bring your notebook to class tomorrow." },
  { word: "nothing", sentence: "There is nothing left inside the empty box." },
  { word: "notice", sentence: "Did you notice the new poster on the wall?" },
  { word: "November", sentence: "November comes right before December." },
  { word: "now", sentence: "We must leave for school right now." },
  { word: "number", sentence: "A circle looks just like the number zero." },
  { word: "nurse", sentence: "The nurse gave me a sticker at the hospital." },
  { word: "ocean", sentence: "A whale is a giant animal that lives in the ocean." },
  { word: "o'clock", sentence: "The school bell rings at eight o'clock." },
  { word: "October", sentence: "We see many orange pumpkins in October." },
  { word: "of", sentence: "I would like a glass of cold water." },
  { word: "off", sentence: "Take off your hat when you are inside." },
  { word: "office", sentence: "My mom is very busy working in the office." },
  { word: "officer", sentence: "The police officer helps keep our streets safe." },
  { word: "often", sentence: "It often rains a lot during the month of April." },
  { word: "oil", sentence: "We use oil to fry the golden chicken." },
  { word: "OK", sentence: "It is OK to make mistakes when you learn." },
  { word: "old", sentence: "My grandfather tells me many old stories." },
  { word: "on", sentence: "Look at that tiny ant crawling on the leaf." },
  { word: "one", sentence: "The table has one broken leg." },
  { word: "only", sentence: "He is the only son in his family." },
  { word: "open", sentence: "I used a key to open the front door." },
  { word: "or", sentence: "Do you want an apple or a banana?" },
  { word: "orange", sentence: "The orange fox hid behind the bushes." },
  { word: "order", sentence: "We would like to order a large pizza." },
  { word: "other", sentence: "The other shoe is under the bed." },
  { word: "out", sentence: "We can go out if it stops raining." },
  { word: "outside", sentence: "I want to play outside, but it is raining." },
  { word: "over", sentence: "I have a few friends coming over to play." },
  { word: "own", sentence: "I have my own bedroom at home." },
  { word: "ox", sentence: "The ox is a very strong animal on the farm." },
  { word: "package", sentence: "The mailman brought a large package to our door." },
  { word: "page", sentence: "Please write your name at the top of the page." },
  { word: "paint", sentence: "I joined the art club to learn how to paint." },
  { word: "pair", sentence: "I have a pair of shiny black shoes." },
  { word: "palace", sentence: "The king lives in a very large and beautiful palace." },
  { word: "pants", sentence: "I wear a black belt with my pants." },
  { word: "papaya", sentence: "A papaya is a sweet fruit with many black seeds." },
  { word: "paper", sentence: "Be careful when you cut the paper." },
  { word: "parent", sentence: "It is not good to tell a lie to your parents." },
  { word: "park", sentence: "The park is very far from my house." },
  { word: "parrot", sentence: "A colorful parrot can learn how to talk." },
  { word: "party", sentence: "I am having a party for my birthday today!" },
  { word: "pass", sentence: "Please pass me the salt and pepper." },
  { word: "pay", sentence: "You must pay for the candy at the counter." },
  { word: "peach", sentence: "I ate a juicy peach during my lunch break." },
  { word: "pear", sentence: "A pear is a fruit that is shaped like a bell." },
  { word: "pen", sentence: "I am learning how to write with a pen." },
  { word: "pencil", sentence: "Do you have any pencils I can borrow?" },
  { word: "people", sentence: "There are many cars and people in the big city." },
  { word: "perhaps", sentence: "Perhaps it will stop raining in the afternoon." },
  { word: "person", sentence: "My mother is a very dear person to me." },
  { word: "pet", sentence: "My favorite pet is a small white rabbit." },
  { word: "phone", sentence: "The secretary answers the phone in the office." },
  { word: "photo", sentence: "I took a photo of my dog with my camera." },
  { word: "piano", sentence: "You must practice the piano every day." },
  { word: "pick", sentence: "Pick up the toy and put it away." },
  { word: "picnic", sentence: "It was a nice and sunny day for a picnic." },
  { word: "picture", sentence: "I love to draw pictures of animals." },
  { word: "pie", sentence: "My mother baked a delicious apple pie." },
  { word: "piece", sentence: "Please give me a piece of paper." },
  { word: "pig", sentence: "The pink pig is playing in the dirt." },
  { word: "pilot", sentence: "The pilot flies the airplane high in the sky." },
  { word: "pin", sentence: "Use a pin to put the picture on the wall." },
  { word: "pink", sentence: "The girl is wearing a pretty pink dress." },
  { word: "pizza", sentence: "I like to eat pizza for dinner." },
  { word: "place", sentence: "There are many beautiful places in the world." },
  { word: "plan", sentence: "We should plan a fun trip for the weekend." },
  { word: "planet", sentence: "The earth is the planet where we all live." },
  { word: "plant", sentence: "That plant is alive because I give it water." },
  { word: "plate", sentence: "The cups and plates are inside the kitchen cupboard." },
  { word: "play", sentence: "I have a few friends coming over to play." },
  { word: "player", sentence: "There are eleven players on a soccer team." },
  { word: "playground", sentence: "Let's run around the playground three times." },
  { word: "please", sentence: "Please give me an apple for my snack." },
  { word: "pocket", sentence: "I have a small toy in my pocket." },
  { word: "police", sentence: "The police officer helps keep our streets safe." },
  { word: "policeman", sentence: "The policeman is standing at the corner." },
  { word: "polite", sentence: "Always be polite and say \"Please\" and \"Thank you.\"" },
  { word: "pond", sentence: "The yellow duck is swimming in the pond." },
  { word: "pool", sentence: "It is a bad idea to run near the pool." },
  { word: "poor", sentence: "The poor dog looks hungry." },
  { word: "popcorn", sentence: "I like to eat popcorn while watching a movie." },
  { word: "popular", sentence: "Soccer is a very popular sport at our school." },
  { word: "pork", sentence: "We had pork chops for dinner." },
  { word: "possible", sentence: "It is possible to finish the work before noon." },
  { word: "post office", sentence: "I went to the post office to send a letter." },
  { word: "postcard", sentence: "My aunt sent me a postcard from her trip." },
  { word: "pot", sentence: "There is hot soup inside the large pot." },
  { word: "practice", sentence: "If you don't practice, you might fail the test." },
  { word: "pray", sentence: "Many people pray before they eat their meal." },
  { word: "prepare", sentence: "Help me prepare the table for dinner." },
  { word: "pretty", sentence: "The girl is wearing a pretty pink dress." },
  { word: "prince", sentence: "The prince will become a king one day." },
  { word: "princess", sentence: "The princess lives in a golden palace." },
  { word: "prize", sentence: "He won a gold medal as a prize for the race." },
  { word: "problem", sentence: "This math problem is very easy to solve." },
  { word: "program", sentence: "My favorite TV program starts at six o'clock." },
  { word: "proud", sentence: "I am proud of you for trying your best." },
  { word: "pull", sentence: "Please pull the door to open it." },
  { word: "pumpkin", sentence: "We see many orange pumpkins in October." },
  { word: "puppy", sentence: "My puppy likes to sleep on my bed." },
  { word: "purple", sentence: "My favorite flower in the garden is purple." },
  { word: "push", sentence: "You need to push the button to start the game." },
  { word: "put", sentence: "I put all my school books in my bag." },
  { word: "queen", sentence: "The king and queen live in a beautiful castle." },
  { word: "question", sentence: "Please raise your hand if you have a question." },
  { word: "quick", sentence: "Be quick, or we will be late!" },
  { word: "quiet", sentence: "Please be quiet while the teacher is speaking." },
  { word: "rabbit", sentence: "Watch the rabbit hop across the grass." },
  { word: "radio", sentence: "We listened to the news on the radio." },
  { word: "railroad", sentence: "The train moves very fast along the railroad." },
  { word: "rain", sentence: "The sky is gray because it is going to rain." },
  { word: "rainbow", sentence: "I can see a beautiful rainbow in the sky." },
  { word: "rainy", sentence: "It was a very rainy and cold yesterday." },
  { word: "raise", sentence: "Please raise your hand if you have a question." },
  { word: "rat", sentence: "A small rat ran across the dark kitchen." },
  { word: "read", sentence: "I am reading a very funny book." },
  { word: "ready", sentence: "I wake up early to get ready for school." },
  { word: "real", sentence: "Have you ever seen a real elephant?" },
  { word: "recorder", sentence: "We are learning how to play the recorder in music class." },
  { word: "red", sentence: "My dad drives a red car to work." },
  { word: "refrigerator", sentence: "Please put the milk back in the refrigerator." },
  { word: "remember", sentence: "Please remember to wash your hands in the bathroom." },
  { word: "repeat", sentence: "Please repeat after me: \"Hello, how are you?\"" },
  { word: "reporter", sentence: "The reporter is telling the news on television." },
  { word: "restroom", sentence: "May I go to the restroom, please?" },
  { word: "rice", sentence: "I like to eat rice and vegetables for lunch." },
  { word: "rich", sentence: "The king in the story was very rich and powerful." },
  { word: "ride", sentence: "I can ride a bicycle without help." },
  { word: "right", sentence: "I have five fingers on my right hand." },
  { word: "ring", sentence: "The school bell rings at eight o'clock." },
  { word: "river", sentence: "We walked along the river and saw many ducks." },
  { word: "road", sentence: "Look at the sign that says \"Stop\" on the road." },
  { word: "robot", sentence: "That big toy robot is too expensive to buy." },
  { word: "ROC", sentence: "ROC is the short name for our country." },
  { word: "rock", sentence: "The rock is very hard and heavy." },
  { word: "roller-blade", sentence: "I am learning how to roller-blade in the park." },
  { word: "roller-skate", sentence: "Can you roller-skate as fast as your brother?" },
  { word: "roof", sentence: "My house has a red roof and a white door." },
  { word: "room", sentence: "I need to get my jacket from the room." },
  { word: "rose", sentence: "There are many red roses in our garden." },
  { word: "rough", sentence: "The skin of the pineapple feels very rough." },
  { word: "round", sentence: "The ball is round." },
  { word: "run", sentence: "It is a bad idea to run near the pool." },
  { word: "sad", sentence: "Don't be sad; we can play again tomorrow." },
  { word: "safe", sentence: "The police officer helps keep our streets safe." },
  { word: "sailor", sentence: "The sailor works on a big ship in the ocean." },
  { word: "salad", sentence: "A tomato is a red fruit we use in salad." },
  { word: "salesman", sentence: "The salesman is showing us a new toy." },
  { word: "salt", sentence: "Please pass me the salt and pepper." },
  { word: "sandwich", sentence: "I want a ham and cheese sandwich." },
  { word: "Saturday", sentence: "I like to go to the park on Saturday." },
  { word: "save", sentence: "My dad goes to the bank to save his money." },
  { word: "say", sentence: "Please say hi to your mother for me." },
  { word: "school", sentence: "I am a happy student at this school." },
  { word: "science", sentence: "We learn about plants and animals in science class." },
  { word: "scientist", sentence: "A scientist does many experiments in a lab." },
  { word: "scooter", sentence: "I like to ride my pink scooter to the park." },
  { word: "sea", sentence: "I love to swim in the blue sea in summer." },
  { word: "seat", sentence: "Please find a seat and sit down quietly." },
  { word: "second", sentence: "I am a student in the second grade." },
  { word: "secretary", sentence: "The secretary answers the phone in the office." },
  { word: "see", sentence: "I see a cat and an owl in the tree." },
  { word: "seesaw", sentence: "Let's play on the seesaw together at the playground." },
  { word: "sell", sentence: "They sell fresh fruit at the market." },
  { word: "send", sentence: "I went to the post office to send a letter." },
  { word: "senior high school", sentence: "My cousin is a student in senior high school." },
  { word: "September", sentence: "We start our new class in September." },
  { word: "serious", sentence: "The teacher looked serious during the test." },
  { word: "set", sentence: "Help me set the table for dinner, please." },
  { word: "seven", sentence: "My brother is seven years of age." },
  { word: "seventy", sentence: "My grandfather is seventy years old now." },
  { word: "several", sentence: "I have several colorful stickers in my book." },
  { word: "shake", sentence: "Please shake the bottle before you drink it." },
  { word: "share", sentence: "I will share my apple and give you half." },
  { word: "shark", sentence: "A shark has many sharp teeth and lives in the sea." },
  { word: "sharp", sentence: "Be careful because the pencil is very sharp." },
  { word: "she", sentence: "She is the fastest runner in our grade." },
  { word: "sheep", sentence: "We saw many cows and sheep on the farm." },
  { word: "shelf", sentence: "Put the book back on the shelf, please." },
  { word: "shell", sentence: "I found a beautiful shell on the beach." },
  { word: "ship", sentence: "The sailor works on a big ship in the ocean." },
  { word: "shirt", sentence: "The kid is wearing a bright yellow shirt." },
  { word: "shoe", sentence: "Don't walk in the mud with your new shoes!" },
  { word: "shop", sentence: "The shop is near my house, so it is convenient." },
  { word: "short", sentence: "February is the shortest month of the year." },
  { word: "shorts", sentence: "I like to wear shorts when it is hot outside." },
  { word: "should", sentence: "You should brush your teeth every morning and night." },
  { word: "shout", sentence: "Please do not shout inside the classroom." },
  { word: "show", sentence: "The salesman is showing us a new toy." },
  { word: "shower", sentence: "I take a warm shower every evening." },
  { word: "shy", sentence: "The new student is a little bit shy." },
  { word: "sick", sentence: "I go to see the doctor when I feel sick." },
  { word: "side", sentence: "The goat is eating grass on the side of the hill." },
  { word: "sidewalk", sentence: "I use white chalk to draw on the sidewalk." },
  { word: "sight", sentence: "The sunset is a beautiful sight." },
  { word: "sign", sentence: "Look at the sign that says \"Stop\" on the road." },
  { word: "simple", sentence: "This is a simple game that anyone can play." },
  { word: "sing", sentence: "Mrs. Lee teaches us how to sing." },
  { word: "singer", sentence: "He is a famous singer that everyone knows." },
  { word: "sir", sentence: "Yes, sir, I will do it." },
  { word: "sister", sentence: "My sister has very long and black hair." },
  { word: "sit", sentence: "The cat is sitting by the window." },
  { word: "six", sentence: "I have six pencils in my pencil case." },
  { word: "sixty", sentence: "There are sixty minutes in one hour." },
  { word: "skate", sentence: "I like to skate on the ice in the winter." },
  { word: "skirt", sentence: "She is wearing a blue skirt." },
  { word: "sky", sentence: "A bird can fly high in the sky." },
  { word: "sleep", sentence: "My cat likes to sleep on the sofa." },
  { word: "slide", sentence: "I like to slide down the big slide at the park." },
  { word: "slow", sentence: "A turtle is a very slow animal." },
  { word: "small", sentence: "The small mouse is afraid of the big cat." },
  { word: "smart", sentence: "A dolphin is a very smart animal that lives in the sea." },
  { word: "smell", sentence: "The bread from the bakery smells very good." },
  { word: "smile", sentence: "Use your mouth to speak clearly and smile." },
  { word: "smoke", sentence: "We saw smoke coming out of the chimney." },
  { word: "snake", sentence: "A long snake is crawling through the grass." },
  { word: "snack", sentence: "Please give me an apple for my snack." },
  { word: "snow", sentence: "We saw white snow on top of the tall mountain." },
  { word: "snowy", sentence: "The mountain looks beautiful on a snowy day." },
  { word: "so", sentence: "It was raining, so we stayed inside the house." },
  { word: "soccer", sentence: "The boy is playing soccer with his friends." },
  { word: "socks", sentence: "My socks are in the top drawer of the desk." },
  { word: "sofa", sentence: "My cat likes to sleep on the sofa." },
  { word: "soldier", sentence: "The soldier wears a green uniform." },
  { word: "some", sentence: "Please give me some paper." },
  { word: "something", sentence: "I want to eat something sweet." },
  { word: "sometimes", sentence: "I sometimes walk to school." },
  { word: "somewhere", sentence: "I lost my pencil somewhere in the classroom." },
  { word: "son", sentence: "He is the only son in his family." },
  { word: "song", sentence: "We sang a happy song in music class." },
  { word: "soon", sentence: "Dinner will be ready very soon." },
  { word: "sore", sentence: "My legs are sore from running all day." },
  { word: "sorry", sentence: "I am sorry I broke your toy." },
  { word: "sound", sentence: "That sounds like a great idea." },
  { word: "soup", sentence: "Be careful; the soup is very hot." },
  { word: "south", sentence: "The birds fly south for the winter." },
  { word: "space", sentence: "This is my favorite book about space." },
  { word: "spaghetti", sentence: "I love to eat spaghetti with tomato sauce." },
  { word: "speak", sentence: "Please be quiet while the teacher is speaking." },
  { word: "special", sentence: "Today is a special day because it is my birthday." },
  { word: "spell", sentence: "How do you spell your name?" },
  { word: "spend", sentence: "I like to spend time playing with my dog." },
  { word: "spider", sentence: "We should not kill the spiders in the garden." },
  { word: "spoon", sentence: "We use a spoon to eat our soup." },
  { word: "sport", sentence: "Soccer is a very popular sport at our school." },
  { word: "spring", sentence: "Flowers grow in the spring." },
  { word: "square", sentence: "A window is often shaped like a square." },
  { word: "stairs", sentence: "Walk down the stairs carefully, please." },
  { word: "stamp", sentence: "Please put a stamp on your letter before you mail it." },
  { word: "stand", sentence: "Please stand up when the teacher enters." },
  { word: "star", sentence: "Look up at the stars in the night sky." },
  { word: "start", sentence: "Summer usually starts in the month of June." },
  { word: "station", sentence: "We took a yellow taxi to get to the train station." },
  { word: "stay", sentence: "We are staying at home today." },
  { word: "steak", sentence: "We had steak for dinner." },
  { word: "sticker", sentence: "You can have this sticker; it is free." },
  { word: "still", sentence: "Although it was raining, we still had fun at the park." },
  { word: "stomach", sentence: "My stomach is full after eating dinner." },
  { word: "stop", sentence: "We can go out if it stops raining." },
  { word: "store", sentence: "The clerk at the store helped us find the milk." },
  { word: "story", sentence: "My grandfather tells me many old stories." },
  { word: "straight", sentence: "Use a ruler to draw a straight line." },
  { word: "strange", sentence: "Strange things always happen in fairy tales." },
  { word: "strawberry", sentence: "I love to eat a red strawberry with sugar." },
  { word: "street", sentence: "You should always cross the street with an adult." },
  { word: "strong", sentence: "The ox is a very strong animal on the farm." },
  { word: "student", sentence: "I am a happy student at this school." },
  { word: "study", sentence: "If you do not study, you might fail the test." },
  { word: "stupid", sentence: "It is a stupid idea to run across the road." },
  { word: "successful", sentence: "He was successful and won the gold medal." },
  { word: "sugar", sentence: "I love to eat a red strawberry with sugar." },
  { word: "summer", sentence: "I love to swim in the blue sea in summer." },
  { word: "sun", sentence: "The sun is low in the sky during the evening." },
  { word: "Sunday", sentence: "We stay at home and rest on Sunday." },
  { word: "sunflower", sentence: "A sunflower is a tall flower with yellow petals." },
  { word: "sunny", sentence: "Today is a beautiful and sunny day." },
  { word: "supermarket", sentence: "My father will drive us to the supermarket." },
  { word: "supper", sentence: "We eat supper in the evening." },
  { word: "sure", sentence: "Are you sure you have your house key?" },
  { word: "surf", sentence: "Some people like to surf on big waves." },
  { word: "surprise", sentence: "There is a surprise gift inside this box." },
  { word: "sweater", sentence: "I am wearing a warm sweater because it is winter." },
  { word: "sweet", sentence: "I ate a sweet bun for my afternoon snack." },
  { word: "swim", sentence: "I love to swim in the blue sea in summer." },
  { word: "swimming", sentence: "I am going swimming with my friends this afternoon." },
  { word: "swing", sentence: "I like to swing high on the playground." },
  { word: "table", sentence: "The light is hanging above the dining table." },
  { word: "take", sentence: "Take off your hat when you are inside." },
  { word: "talk", sentence: "A colorful parrot can learn how to talk." },
  { word: "tall", sentence: "He is as tall as his older brother." },
  { word: "tape", sentence: "I used tape to fix the ripped paper." },
  { word: "taste", sentence: "The candy tastes very sweet and yummy." },
  { word: "taxi", sentence: "We took a yellow taxi to get to the train station." },
  { word: "tea", sentence: "My mom likes to drink hot tea in the morning." },
  { word: "teach", sentence: "My mother will teach me how to cook rice." },
  { word: "teacher", sentence: "Please be quiet while the teacher is speaking." },
  { word: "team", sentence: "He is the leader of our school soccer team." },
  { word: "teenager", sentence: "My brother is a teenager who is 15 years old." },
  { word: "telephone", sentence: "I am talking to my grandmother on the telephone." },
  { word: "television", sentence: "The reporter is telling the news on television." },
  { word: "tell", sentence: "It is not good to tell a lie to your parents." },
  { word: "temperature", sentence: "The doctor checked my temperature because I felt hot." },
  { word: "ten", sentence: "I have ten fingers on my hands." },
  { word: "tennis", sentence: "He is very good at playing tennis." },
  { word: "terrible", sentence: "The weather was terrible with a lot of rain." },
  { word: "test", sentence: "If you do not study, you might fail the test." },
  { word: "than", sentence: "My sister is tall, and she is even taller than me." },
  { word: "thank", sentence: "Always say thank you when someone helps you." },
  { word: "that", sentence: "That is a very big elephant!" },
  { word: "the", sentence: "I see a cat and an owl in the tree." },
  { word: "theater", sentence: "We went to the theater to watch a funny play." },
  { word: "then", sentence: "First wash your hands, then eat." },
  { word: "there", sentence: "There is a toy inside the heavy box." },
  { word: "these", sentence: "I want to build a tall tower with these blocks." },
  { word: "they", sentence: "They are my friends." },
  { word: "thick", sentence: "This thick book has many pages to read." },
  { word: "thin", sentence: "The paper is very thin and easy to tear." },
  { word: "thing", sentence: "What is that strange thing on the table?" },
  { word: "think", sentence: "I need some time to think about the answer." },
  { word: "third", sentence: "I am in the third grade." },
  { word: "thirsty", sentence: "I am thirsty; may I have a glass of water?" },
  { word: "thirteen", sentence: "My older cousin is thirteen years old." },
  { word: "thirty", sentence: "Some months have thirty days in them." },
  { word: "this", sentence: "This is the end of the long movie." },
  { word: "those", sentence: "Please let me help you carry those bags." },
  { word: "though", sentence: "He went to school though he felt a little tired." },
  { word: "thought", sentence: "I thought about the answer for a long time." },
  { word: "three", sentence: "We visited the zoo three weeks ago." },
  { word: "throat", sentence: "My throat feels sore when I have a cold." },
  { word: "through", sentence: "I can see the rain through the window." },
  { word: "throw", sentence: "Can you throw the basketball into the net?" },
  { word: "thumb", sentence: "Give a \"thumbs up\" with your thumb if you are ready." },
  { word: "Thursday", sentence: "I play with my friends every Thursday." },
  { word: "ticket", sentence: "You need a ticket to enter the movie theater." },
  { word: "tidy", sentence: "Please keep your desk clean and tidy." },
  { word: "tie", sentence: "Can you help me tie my shoelaces?" },
  { word: "tiger", sentence: "Can you run as fast as a tiger?" },
  { word: "time", sentence: "What time did you arrive at school today?" },
  { word: "tired", sentence: "He went to school though he felt a little tired." },
  { word: "to", sentence: "I go to bed early every night." },
  { word: "today", sentence: "Today is a beautiful and sunny day." },
  { word: "toe", sentence: "I stubbed my big toe on the table." },
  { word: "together", sentence: "We run down the green hill together." },
  { word: "tomato", sentence: "A tomato is a red fruit we use in salad." },
  { word: "tomorrow", sentence: "Please bring your notebook to class tomorrow." },
  { word: "tongue", sentence: "Be careful not to bite your tongue." },
  { word: "tonight", sentence: "My dad is going to cook dinner for us tonight." },
  { word: "too", sentence: "I like ice cream, and my brother likes it too." },
  { word: "tooth", sentence: "I lost my front tooth yesterday!" },
  { word: "top", sentence: "There is a red cherry on top of my ice cream." },
  { word: "touch", sentence: "Don't touch the stove, or you might burn your hand." },
  { word: "towel", sentence: "Use a towel to make your hands dry." },
  { word: "town", sentence: "We live in a small and quiet town." },
  { word: "toy", sentence: "There is a toy inside the heavy box." },
  { word: "traffic", sentence: "There are many cars in the traffic today." },
  { word: "train", sentence: "The train moves very fast along the railroad." },
  { word: "travel", sentence: "I want to travel around the world one day." },
  { word: "tree", sentence: "I see a cat and an owl in the tree." },
  { word: "trip", sentence: "My aunt sent me a postcard from her trip." },
  { word: "trouble", sentence: "Please stay out of trouble and follow the rules." },
  { word: "truck", sentence: "A big red truck is carrying many heavy boxes." },
  { word: "true", sentence: "Is it true that cats can see in the dark?" },
  { word: "try", sentence: "Please try your best to finish the puzzle." },
  { word: "T-shirt", sentence: "I am wearing a white T-shirt with a blue star." },
  { word: "Tuesday", sentence: "We have music class every Tuesday afternoon." },
  { word: "turkey", sentence: "We eat turkey during big family dinners." },
  { word: "turn", sentence: "Please turn on the fan; it is very hot." },
  { word: "turtle", sentence: "A turtle is a very slow animal." },
  { word: "twelve", sentence: "We eat our lunch at twelve o'clock every day." },
  { word: "twenty", sentence: "Can you count from one to twenty in English?" },
  { word: "two", sentence: "I have two eyes and two ears." },
  { word: "typhoon", sentence: "We stay inside the house during a typhoon." },
  { word: "umbrella", sentence: "Take your umbrella because it is going to rain." },
  { word: "uncle", sentence: "My uncle lives in a big city in China." },
  { word: "under", sentence: "The other shoe is under the bed." },
  { word: "understand", sentence: "Please nod your head if you understand the rules." },
  { word: "uniform", sentence: "The soldier wears a green uniform." },
  { word: "university", sentence: "My older brother studies hard at a university." },
  { word: "unusual", sentence: "I saw an unusual bird with very bright feathers." },
  { word: "up", sentence: "Look up at the stars in the night sky." },
  { word: "USA", sentence: "My uncle lives in a very large city in the USA." },
  { word: "use", sentence: "We use a spoon to eat our soup." },
  { word: "useful", sentence: "A flashlight is very useful when it is dark." },
  { word: "usually", sentence: "I usually brush my teeth after I eat dinner." },
  { word: "vacation", sentence: "We stayed in a nice hotel during our vacation." },
  { word: "vegetable", sentence: "Broccoli is a healthy green vegetable." },
  { word: "very", sentence: "That is a very big elephant!" },
  { word: "video", sentence: "We can find many cool videos on the internet." },
  { word: "village", sentence: "My grandfather lives in a small village near the mountains." },
  { word: "violin", sentence: "She can play a beautiful song on the violin." },
  { word: "visit", sentence: "The foreigner is visiting our city for the first time." },
  { word: "voice", sentence: "She is a very good singer with a sweet voice." },
  { word: "wait", sentence: "I wait for the school bus every morning." },
  { word: "waiter", sentence: "The waiter brought us some yummy pizza." },
  { word: "waitress", sentence: "The waitress at the restaurant was very nice." },
  { word: "wake", sentence: "I wake up early to get ready for school." },
  { word: "walk", sentence: "A blind person uses a white cane to walk." },
  { word: "wall", sentence: "Use a pin to put the picture on the wall." },
  { word: "wallet", sentence: "My dad keeps his money inside his brown wallet." },
  { word: "want", sentence: "I want to buy a new book today." },
  { word: "warm", sentence: "I take a warm bath every night." },
  { word: "wash", sentence: "Please wash your face before you go to bed." },
  { word: "watch", sentence: "Look ahead and watch where you are walking." },
  { word: "water", sentence: "I like to have ice in my water." },
  { word: "watermelon", sentence: "A watermelon is big, green, and red inside." },
  { word: "way", sentence: "We used a map to find the way to the zoo." },
  { word: "we", sentence: "We are staying at home today." },
  { word: "weak", sentence: "I felt weak when I had a bad cold." },
  { word: "wear", sentence: "He wears a blue cap to protect his head." },
  { word: "weather", sentence: "The weather is usually very nice in April." },
  { word: "Wednesday", sentence: "Wednesday is the middle of the school week." },
  { word: "week", sentence: "We visited the zoo three weeks ago." },
  { word: "weekend", sentence: "Let's go to the zoo this weekend." },
  { word: "welcome", sentence: "You are always welcome in our house." },
  { word: "well", sentence: "You should chew your food well." },
  { word: "west", sentence: "The sun sets in the west." },
  { word: "wet", sentence: "My clothes got wet in the rain." },
  { word: "whale", sentence: "A whale is a giant animal that lives in the ocean." },
  { word: "what", sentence: "What do you want to do after school?" },
  { word: "wheel", sentence: "My dad can fix my broken bicycle wheel." },
  { word: "when", sentence: "Please call me when you get home." },
  { word: "where", sentence: "Look ahead and watch where you are walking." },
  { word: "whether", sentence: "I don't know whether it will rain today or not." },
  { word: "which", sentence: "Which animal is your favorite at the zoo?" },
  { word: "while", sentence: "Please be quiet while the teacher is speaking." },
  { word: "white", sentence: "We saw a white boat on the blue lake." },
  { word: "who", sentence: "Who is your favorite teacher?" },
  { word: "whole", sentence: "Blue is my favorite color in the whole world." },
  { word: "whose", sentence: "Whose book is this sitting on my desk?" },
  { word: "why", sentence: "Why are you crying, little boy?" },
  { word: "wife", sentence: "My mother is my father's wife." },
  { word: "will", sentence: "I will share my apple and give you half." },
  { word: "win", sentence: "I hope our team can win the game." },
  { word: "wind", sentence: "The wind feels very cool this evening." },
  { word: "window", sentence: "The cat is sitting by the window." },
  { word: "windy", sentence: "I love to fly my red kite on a windy day." },
  { word: "winter", sentence: "It is very cold in the winter." },
  { word: "wise", sentence: "My grandfather is very wise." },
  { word: "with", sentence: "The boy is playing soccer with his friends." },
  { word: "without", sentence: "I can ride a bicycle without help." },
  { word: "woman", sentence: "That woman is my grandmother's best friend." },
  { word: "wonderful", sentence: "My grandfather tells me many wonderful stories." },
  { word: "wood", sentence: "My dad will chop the wood for the fire." },
  { word: "word", sentence: "Use a dictionary to find the meaning of new words." },
  { word: "work", sentence: "My dad drives a red car to work." },
  { word: "workbook", sentence: "Please open your workbook to page ten." },
  { word: "worker", sentence: "The worker is fixing the road near our house." },
  { word: "world", sentence: "Blue is my favorite color in the whole world." },
  { word: "worry", sentence: "Do not worry; everything will be okay." },
  { word: "wrap", sentence: "I will wrap the gift in beautiful paper." },
  { word: "write", sentence: "I sit at my desk to draw pictures and write." },
  { word: "writer", sentence: "The writer wrote a very funny storybook." },
  { word: "wrong", sentence: "It is okay if your answer is wrong; just try again." },
  { word: "yard", sentence: "I like to play badminton with my sister in the yard." },
  { word: "year", sentence: "We go to summer camp every year." },
  { word: "yellow", sentence: "The kid is wearing a bright yellow shirt." },
  { word: "yes", sentence: "Yes, I would love to have a cookie." },
  { word: "yesterday", sentence: "We had a great time at the zoo yesterday." },
  { word: "yet", sentence: "I have not finished my homework yet." },
  { word: "you", sentence: "This birthday gift is for you." },
  { word: "young", sentence: "The young boy is learning how to ride a bike." },
  { word: "your", sentence: "How do you spell your name?" },
  { word: "yummy", sentence: "The waiter brought us some yummy pizza." },
  { word: "zebra", sentence: "A zebra looks like a horse with black and white stripes." },
  { word: "zero", sentence: "A circle looks just like the number zero." },
  { word: "zoo", sentence: "Let's go to the zoo this weekend." }
];

// --- 自動處理程式碼 (每次網頁載入時自動排序並編號) ---
// 1. 依照字母順序 (A-Z) 排序
// 2. 自動分配 Session (每 50 個字一組)
const masterWordList = rawWordData
  .sort((a, b) => a.word.toLowerCase().localeCompare(b.word.toLowerCase()))
  .map((item, index) => ({
    session: Math.floor(index / 50) + 1, // 計算 Session：0~49 為 Session 1, 50~99 為 Session 2...
    word: item.word,
    sentence: item.sentence
  }));